from pathlib import Path
#string paths
TRAIN_DATASET_STR_PATH = 'dataset/train.txt'
TEST_DATASET_STR_PATH = 'dataset/test.txt'
# VAL_DATASET_STR_PATH = '../dataset/val.txt'
PICKLED_TFIDF_STR_PATH = 'tfidf.pkl'
PICKLED_NAIVE_BAYES_STR_PATH = 'nb.pkl'
PICKLED_ER_MODEL_STR_PATH = 'erm.pkl'

#path objs
TRAIN_DATASET_PATH = Path(TRAIN_DATASET_STR_PATH)
TEST_DATASET_PATH = Path(TEST_DATASET_STR_PATH)
PICKLED_TFIDF_PATH = Path(PICKLED_TFIDF_STR_PATH)
PICKLED_NAIVE_BAYES_PATH = Path(PICKLED_NAIVE_BAYES_STR_PATH)
PICKLED_ER_MODEL_PATH = Path(PICKLED_ER_MODEL_STR_PATH)
# VAL_DATASET_PATH = Path(TRAIN_DATASET_STR_PATH)